name: libiamf-builder

description: Build libiamf.

inputs:
  build-options:
    description: Options in build command
    required: false
    default: ""

runs:
  using: composite
  steps:
    - shell: bash
      run: |
        cd code
        cmake .
        make

